# Openstack Config
os_username=admin
os_password=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx
os_auth_url=http://172.27.104.1:5000/v3
os_local_domain=local

# Super Config
supr_username=api-c-10-2
supr_password=XXXXXXXXXXXXXXXXXXXXXXX
supr_base_url=https://api.supr.naiss.se/api
supr_centre_id=10
supr_ssc_resource=Cloud
supr_local_resource=Tjosan

# Approved admins
#approved_admins=10359,16927
approved_admins=10359

# Log level
#
# 0 no logs
# 1 errors
# 2 warnings
# 3 info
# 4 debug
log_level=4
log_file=/var/log/suprsync.log

# Keep track of last sync
state_file=/usr/local/share/suprsync/suprsync.state

# Network
ext_net=Public External IPv4 Network
ext_dns=130.239.1.90
int_cidr=10.35.3.0/24
int_gw=10.35.3.1
