cloud_name: dev-cirrus
record_info:
  center: SE-SNIC-C3SE
  resource: cirrus.c3se.chalmers.se 
  storage_resource: cirrus.c3se.chalmers.se
  storage_share: block
  storage_media: disk
database:
  name: devel
  port: 5432
  host: cirrus-accounting
  user: devel
supr:
  api_base_url: https://api.supr.naiss.se/api
  resource_id: 111
  storage_id: 112
  #api_base_url: https://disposer.c3se.chalmers.se/supr-test/api
  #resource_id: '64'
  #storage_id: '63'
  #api_base_url: https://api.blender.c3se.chalmers.se/f/api
    #resource_id: '100'
    #storage_id: '101'
accounting:
  sampling_frequency: 900  # in seconds
  project_pattern: '^C3SE \d{4}/\d-\d+'
  spool_directory: '/var/spool/openstack-supr-sync/'
log_file: '/var/log/openstack-supr-sync.log'
log_level: 'INFO'
bad_word_list: '/var/lib/openstack-supr-sync/bad_words.json'
network:
  external_network: dev-public
  external_dns: 129.16.1.53
  internal_gateway: 10.10.10.1
  internal_cidr: 10.10.10.0/24
  external_gateway_ip: 129.16.122.1
